#!/bin/bash

#
# Generates new static content and deploys it to gh-pages branch
#

set -eu

# first of all, make sure everything is up to date from trunk and that we have
# no garbage in the working copy
git checkout .
git checkout gh-pages
git pull

# build the project into an index.html
elm make src/*.elm

# now commit and push
git add index.html
git commit -m "$(date) deployment"
git push

# go back to the previous branch
git checkout -
